#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2020 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    colorscheme = "bluewery"
    ## EXTRA COLOR THEMESE ADDED
    # * nightfly
    # * bluewery_light
    # * bluewery
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = true
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    buffer_index_type = 4
    enable_tabline_filetype_icon = true
    enable_statusline_mode = false
    # ANDREWS CUSTOMIZATIONS
    filemanager = "nerdtree"
    filetree_direction = "left"

# Enable autocomplete layer
[[layers]]
  name = 'autocomplete'
  auto_completion_return_key_behavior = "complete"
  auto_completion_tab_key_behavior = "smart"

[[layers]]
  name = 'shell'
  default_position = 'bottom'
  default_height = 30

[[layers]]
  name = "colorscheme"

[[layers]]
  name = "lang#rust"

[[layers]]
  name = "lang#go"

[[layers]]
  name = "lang#javascript"

[[layers]]
  name = "lsp"

[[layers]
  name = "lang#markdown"

[[layers]]
  name = "lsp"
  filetypes = [
    "rust"
  ]
  [layers.override_cmd]
    rust = ["rls"]

[[custom_plugins]]
  repo = "puremourning/vimspector"
  repo = "bluz71/vim-nightfly-guicolors"
  repo = "relastle/bluewery"]
